# This file was generated by GoReleaser. DO NOT EDIT.
class Manala < Formula
  desc "Let your projects plumbings up to date"
  homepage "https://github.com/manala/manala"
  version "0.14.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/manala/manala/releases/download/0.14.0/manala_Darwin_x86_64.tar.gz"
    sha256 "b0d21a8560935b8fd018cd9d50ac8a07d06065e317290e58fd54043a6f2b0fa5"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/manala/manala/releases/download/0.14.0/manala_Linux_x86_64.tar.gz"
      sha256 "d8b101dcff3906eabf820223acb6c0ecb296db0d2487954cfd599405f3c18063"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/manala/manala/releases/download/0.14.0/manala_Linux_arm64.tar.gz"
        sha256 "738d39a477ac863ea92743124734dbbf214b8f2660bdbba1e0651484d9ad6854"
      else
        url "https://github.com/manala/manala/releases/download/0.14.0/manala_Linux_armv6.tar.gz"
        sha256 "d5c3bcbce7369c06f3b87ce8237fa7fa75d603cef8b723fba5198ceb38524e6d"
      end
    end
  end

  def install
    bin.install "manala"
  end

  test do
    system "#{bin}/manala --version"
  end
end
